// <auto-generated />
namespace RudycommerceLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NullableProperties_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableProperties_product));
        
        string IMigrationMetadata.Id
        {
            get { return "201804101251181_NullableProperties_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
