// <auto-generated />
namespace RudycommerceLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class loc_prod_specprodprop_valueChangedToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loc_prod_specprodprop_valueChangedToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201804071555042_loc_prod_specprodprop_valueChangedToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
